baseURL: https://tigertutoringtool.aamira.me/
languageCode: en-us
title: Tiger Tutoring Tool
theme: PaperMod
googleAnalytics: G-0WWJG03GJY
enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
taxonomies:
  category: categories
  tag: tags
  tinker: tinker


module:
  imports:
  - path: github.com/adityatelange/hugo-PaperMod


params:
  env: production
  title: "Tiger Home Work Help"
  description: "Get help for your classes"
  author: ["Aamir", "Michael"]
  ShowToc: true
  ShowShareButtons: true
  ShowReadingTime: true
  ShowCodeCopyButtons: false
  keywords: [school, help, homework]
  ShowBreadCrumbs: true

  CommentoURL: "https://cdn.commento.io/js/commento.js"


outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  homeInfoParams:
    Title: Hi there
    Content: Let's Learn
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
    assets:


menu:
  main:
    - identifier: home
      name: home
      url: /
      weight: 1
    - identifier: posts
      name: posts
      url: /posts/
      weight: 2
    - identifier: categories
      name: teacher
      url: /categories/
      weight: 10
    - identifier: tags
      name: class
      url: /tags/
      weight: 20
    - indentifier: search
      name: search
      url: /search/
      weight: 30
    - identifier: signin
      name: sign in
      url: /signin/
      weight: 40
