baseURL: https://tigerhomeworkhelp.aamira.me/
languageCode: en-us
title: Tiger Home Work Help
theme: PaperMod
googleAnalytics: G-0WWJG03GJY


module:
  imports:
  - path: github.com/adityatelange/hugo-PaperMod


params:
  env: production
  title: "Tiger Home Work Help"
  description: "Get help for your classes"
  author: ["Aamir", "Michael"]
  defaultTheme: auto
  ShowShareButtons: true
  ShowCodeCopyButtons: false

params:
  homeInfoParams:
    Title: Hi there
    Content: Let's Learn 

menu:
  main:
    - identifier: home
      name: home
      url: /
      weight: 1
    - identifier: categories
      name: categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20

