baseURL: https://tigertutoringtool.aamira.me/
languageCode: en-us
title: Tiger Tutoring Tool
theme: PaperMod
googleAnalytics: G-0WWJG03GJY
enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true


module:
  imports:
  - path: github.com/adityatelange/hugo-PaperMod


params:
  env: production
  title: "Tiger Home Work Help"
  description: "Get help for your classes"
  author: ["Aamir", "Michael"]
  defaultTheme: auto
  ShowShareButtons: true
  ShowReadingTime: true
  showtoc: true
  ShowCodeCopyButtons: false
  images: '/static/tiger.png'
  keywords: [school, help, homework]
  ShowToc: true
  ShowBreadCrumbs: true
  label:
    label.icon: '/static/tiger.png'
    label.iconHeight: 35

params:
  CommentoURL: "https://cdn.commento.io/js/commento.js"




outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  homeInfoParams:
    Title: Hi there
    Content: Let's Learn
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
    assets:
      favicon16x16: "/favicon-16x16.png"
      favicon32x32: "/favicon-32x32.png"

menu:
  main:
    - identifier: home
      name: home
      url: /
      weight: 1
    - identifier: posts
      name: posts
      url: /posts/
      weight: 2
    - identifier: categories
      name: categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - indentifier: search
      name: search
      url: /search/
      weight: 30
    - identifier: signin
      name: sign in
      url: /signin/
      weight: 40
