baseURL: https://tigerhomeworkhelp.aamira.me/
languageCode: en-us
title: Tiger Home Work Help
theme: PaperMod
googleAnalytics: G-0WWJG03GJY

module:
  imports:
  - path: github.com/adityatelange/hugo-PaperMod


params:
  env: production
  title: "Tiger Home Work Help"
  description: "Get help for you classes"
  author: ["Aamir", "Michael"]
  defaultTheme: auto
  ShowShareButtons: true
  ShowCodeCopyButtons: false
  params:
    homeInfoParams:
        Title: Hi there wave
        Content: Can be Info, links, about...
