baseURL: https://tigertutoringtool.aamira.me/
languageCode: en-us
title: Tiger Tutoring Tool
theme: PaperMod
  # googleAnalytics: G-0WWJG03GJY
enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: true
buildFuture: false
buildExpired: false
enableEmoji: true
enableEmoji: true
taxonomies:
  teacher: teacher
  class: class

module:
  imports:
  - path: github.com/adityatelange/hugo-PaperMod


params:
  env: production
  title: "Tiger Home Work Help"
  description: "Get help for your classes"
  author: ["Aamir", "Michael"]
  ShowToc: true
  defaultTheme: auto
  ShowBreadCrumbs: false
  ShowReadingTime: true
  ShowCodeCopyButtons: false
  images: '/static/tiger.png'
  keywords: [school, help, homework]
  label:
    label.icon: 'static/tiger.png'
    label.iconHeight: 35
  fuseOpts:
      isCaseSensitive: false
      shouldSort: true
      location: 0
      distance: 1000
      threshold: 0.4
      minMatchCharLength: 0
      keys: ["title", "permalink", "summary", "content"]
  assets:
    favicon16x16: "/favicon-16x16.png"
    favicon32x32: "/favicon-32x32.png"
  profileMode:
    enabled: true
    title: "<Tiger Tutoring Tool>"
    imageUrl: "tiger.webp"
    imageWidth: 375
    imageHeight: 375
    buttons:
        - name: Browse
          url: "/teacher/"

outputs:
  home:
    - HTML
    - RSS
    - JSON
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: teacher
      name: Teacher
      url: /teacher/
      weight: 10
    - indentifier: search
      name: Search
      url: /search/
      weight: 30
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 40
