baseURL = 'https://tigerhomeworkhelp.aamira.me/'
languageCode = 'en-us'
defaultContentLanguage = 'en'
title = 'Tiger Home Work Help'
theme = 'universal'
googleAnalytics = 'G-0WWJG03GJY'


[[menu.main]]
    name = "Home"
    identifier = "menu.home"
    url = "/"
    weight = 1
