name: Deploy Quartz site to GitHub Pages

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [build]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0 # Fetch all history for git info
          submodules: "recursive"
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - uses: useblacksmith/setup-node@v5
        with:
          node-version: 20
      - name: Install Dependencies
        run: bun install
      - name: Build Quartz
        run: npx quartz build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
