name: Optimize images
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  optimize-images:
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v3
      - name: optimize
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN}}
          ignorePaths: "content/img/avatar_index.gif,quartz/static/**"
          compressOnly: true
      - name: "Commit & push"
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          message: "[CI] Optimize images"
