name: Update module
on:
  repository_dispatch:
    types: [update]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          submodules: recursive
          fetch-depth: 0
      - name: Update module
        run: |
          git submodule update --init --recursive --checkout -f --remote
          git config --global user.name "GitHub Action"
          git config --global user.email "noreply@github.com"
          git commit -am "chore (update): - aamirazad/Notes@${{github.event.client_payload.ref}}"
          git push
